name: Backend PHP CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Copy env file
        run: cp app/env .env

      - name: Install Composer
        run: sudo apt-get update && sudo apt-get install -y composer

      - name: Install dependencies
        working-directory: ./app
        run: composer install

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: Scarlett
        with:
          version: 9.6
          bootstrap: app/vendor/autoload.php
          configuration: app/tests/phpunit.xml
          args: --coverage-text
